# Default values for xavier.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

name: visualization-frontend
env: staging

image:
  registry: khaosdoctor
  name: visualization-frontend
  tag: v1.0.0
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  portName: http

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
  hostname: localhost

environment: {}

resources:
  requests:
    cpu: 250m
    memory: 128M
  limits:
    cpu: 250m
    memory: 256M
