# Default values for xavier.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

name: visualization-backend
env: production
maxReplicas: 10
cpuUsage: 90
memoryUsage: 90

image:
  registry: khaosdoctor
  name: apps40-backend
  tag: v1.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  portName: http

environment: {}

resources:
  requests:
    cpu: 250m
    memory: 128M
  limits:
    cpu: 500m
    memory: 256M
